export const LOGIN_AUTH_USER = 'LOGIN_AUTH_USER'
export const LOGOUT_AUTH_USER = 'LOGOUT_AUTH_USER'
export const QUESTIONS_RECIVE = 'QUESTIONS_RECIVE'
export const QUESTION_ADD = 'QUESTION_ADDN'
export const VOTES_UPDATE = 'VOTES_UPDATE'
export const USERS_RECIVE = 'USERS_RECIVE'
export const USER_ANSWER_ADD = 'USER_ANSWER_ADD'
export const USER_QUESTION_ADD = 'USER_QUESTION_ADD'


